Cleanup old examples, readme, and rename pipelineJava8 to pipelineMaven
ploigos/ploigos-jenkins-library pull request #17
Opened 2020-10-19 15:11 UTC by itewk

2020-10-19 15:15 UTC, kfrankli requested changes

2020-10-19 15:15 UTC, kfrankli commented on README.md
> +## Directly
This seems really awkward

2020-10-19 15:24 UTC, kfrankli approved these changes
Don't let perfection be the enemy of the good.

2020-10-20 14:24 UTC, BillBensing approved these changes
Very clear!

2020-10-20 14:25 UTC, merged