Feature/black pearl
ploigos/ploigos-jenkins-library pull request #27
Opened 2021-02-23 14:38 UTC by redhat-snelson

Implement TLS and Trusted CA fixes needed for working with Nexus Container Registry and Gitea.

2021-02-23 14:42 UTC, andykrohg approved these changes
Lgtm 👍

2021-02-24 14:47 UTC, itewk requested changes

2021-02-24 14:47 UTC, itewk commented on vars/ploigosWorkflowMinimal.groovy
> +        pass the OpenShift CAs into the Containers that Jenkins uses as Agents
drop the "openshift" part and just say "additional CAs"

2021-02-24 15:21 UTC, itewk approved these changes

2021-02-24 15:21 UTC, merged