add new Container Scan workflow
ploigos/ploigos-jenkins-library pull request #33
Opened 2021-04-30 13:38 UTC by mertel-rh

I cleaned up and added the Container Scanning workflow that I worked on with @itewk 
Please make sure I didn't miss anything in my cleanup and that I added the vars correctly to the Map.

2021-04-30 13:48 UTC, itewk requested changes

2021-04-30 13:48 UTC, itewk commented on vars/ploigosWorkflowContainerScan.groovy
> +                                     """
fix indent

2021-04-30 13:48 UTC, itewk commented on vars/ploigosWorkflowContainerScan.groovy
> +    string imageTag = ''
capital S

2021-04-30 13:48 UTC, itewk commented on vars/ploigosWorkflowContainerScan.groovy
> +    string imageName = ''
capital S

2021-04-30 13:48 UTC, itewk commented on vars/ploigosWorkflowContainerScan.groovy
> +    string imageOrg = ''
capital S

2021-04-30 13:48 UTC, itewk commented on vars/ploigosWorkflowContainerScan.groovy
> +    string registryCredentialName = ''
capital S

2021-04-30 13:48 UTC, itewk commented on vars/ploigosWorkflowContainerScan.groovy
> +    string registryURL = ''
capital S

2021-04-30 13:48 UTC, itewk commented on vars/ploigosWorkflowContainerScan.groovy
> +#!/usr/bin/env groovy
lets do `ploigosWorkflowExistingContainerImageScan` to make it clear its for scanning an already built container image.

2021-04-30 15:37 UTC, itewk approved these changes

2021-05-04 20:48 UTC, BillBensing approved these changes

2021-05-04 20:49 UTC, merged